version: 0.2

# Define environment variables
env:
  variables:
    S3_BUCKET: "nodejsappcodeuploading" # Replace with your S3 bucket name
    APP_NAME: "nodejs-app"

phases:
  install:
    commands:
      # Install Node.js dependencies
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      # Run tests
      - echo "Running tests..."
      - npm test

  build:
    commands:
      # Package the application
      - echo "Building the application..."
      - zip -r $APP_NAME.zip .

  post_build:
    commands:
      # Upload the artifact to S3
      - echo "Uploading artifact to S3..."
      - aws s3 cp $APP_NAME.zip s3://$S3_BUCKET/$APP_NAME.zip

artifacts:
  files:
    - "**/*"
  discard-paths: yes